version: "3"

tasks:
  git-setup:
    cmds:
      - pre-commit autoupdate
      - pre-commit install
  merge:
    cmds:
      - meld README.md ~/mnt/nextcloud-personal/shared/system-images/dotfiles-windows/README.md
